context:
  name: ros-humble-tcb-span
  version: "1.0.2"

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/PickNikRobotics/cpp_polyfills.git
  git_rev: 1.0.2

build:
  number: 0
  script:
    - cd tcb_span
    - cmake ${CMAKE_ARGS} -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -S . -B build
    - cmake --build build
    - cmake --install build --prefix $PREFIX 

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - make
    - ros-humble-ament-cmake

test:
  commands:
    - test -f ${PREFIX}/include/tcb_span/span.hpp

about:
  home: https://github.com/PickNikRobotics/cpp_polyfills
  license: BSL-1.0
  summary: Implementation of C++20's std::span