[project]
name = "ros-humble-tcb-span"
version = "1.0.2"
description = "Implementation of C++20's std::span"
authors = ["Tyler Weaver <tyler@picknik.ai>"]
channels = ["conda-forge", "robostack-staging"]
platforms = ["linux-64"]
license = "BSL-1.0"
repository = "https://github.com/PickNikRobotics/cpp_polyfills"

[tasks]
configure = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release"
build = { cmd = "cmake --build build", depends_on = ["configure"] }
test = {cmd = "ctest --test-dir build  --rerun-failed --output-on-failure", depends_on = ["build"] }
install = {cmd = "cmake --install build --prefix install", depends_on = ["build"] }

[dependencies]
ros-humble-ament-cmake = "1.3.3.*"
ros-humble-ament-cmake-gtest = "1.3.3.*"
cmake = "3.27.6.*"
cxx-compiler = "1.6.0.*"
rattler-build = "0.3.1.*"
boa = "0.15.1.*"
